### ISSUE TITLE
Crash on Galaxy note 10 device (SM-N976B)

### ISSUE THREAD

**Issue by srene** [datahop/datahop-android-demo#1]
It seems datahop ipfs-lite library crashes on Galaxy note 10 device. Issue not detected in any other device by now. Here is the log:

04/20 12:07:10: Launching 'app' on samsung SM-N976B.
Install successfully finished in 24 s 326 ms.
$ adb shell am start -n "com.example.datahopdemo/com.example.datahopdemo.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Connected to process 24760 on device 'samsung-sm_n976b-RFCMA015J0K'.
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
D/ActivityThread: handleBindApplication()++ app=com.example.datahopdemo
D/ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
D/ActivityThread: handleBindApplication() -- skipGraphicsSupport=false
    ActivityThread::handleMakeApplication() data=AppBindData{appInfo=ApplicationInfo{c9fc9e7 com.example.datahopdemo}} appContext=android.app.ContextImpl@f378994 appContext.mOpPackageName=com.example.datahopdemo appContext.mBasePackageName=com.example.datahopdemo appContext.mPackageInfo=android.app.LoadedApk@308dc3d data.restrictedBackupMode= false data.providers= [] Caller=android.app.ActivityThread.handleBindApplication:7440 android.app.ActivityThread.access$1500:301 android.app.ActivityThread$H.handleMessage:2148 android.os.Handler.dispatchMessage:106 android.os.Looper.loop:246 
D/LoadedApk: LoadedApk::makeApplication() appContext=android.app.ContextImpl@20e8c32 appContext.mOpPackageName=com.example.datahopdemo appContext.mBasePackageName=com.example.datahopdemo appContext.mPackageInfo=android.app.LoadedApk@308dc3d
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
D/NetworkSecurityConfig: No Network Security Config specified, using platform default
I/DecorView: [INFO] isPopOver=false, config=true
    updateCaptionType >> DecorView@f486d73[], isFloating=false, isApplication=true, hasWindowDecorCaption=false, hasWindowControllerCallback=true
D/DecorView: setCaptionType = 0, this = DecorView@f486d73[]
W/ple.datahopdem: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
    Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
D/-----Version :: 0.0.0
D/Node Status onCreate: false
E/GoLog: 2021-04-20T10:07:35.511Z	[35mDEBUG[0m	datahop	mobile/datahop.go:74	Node Started
D/Node Status onStart: false
E/Go: panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x746bd42140]
    goroutine 16 [running]:
    github.com/libp2p/go-libp2p-swarm.(*Swarm).TransportForListening(0x4000642900, 0x0, 0x0, 0x0, 0x0)
    	/tmp/gomobile-work-225845036/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.4.0/swarm_transport.go:43 +0x30
    github.com/libp2p/go-libp2p-swarm.(*Swarm).AddListenAddr(0x4000642900, 0x0, 0x0, 0x0, 0x0)
    	/tmp/gomobile-work-225845036/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.4.0/swarm_listen.go:41 +0x30
    github.com/libp2p/go-libp2p-swarm.(*Swarm).Listen(0x4000642900, 0x4000674450, 0x3, 0x3, 0x4000124000, 0x0)
    	/tmp/gomobile-work-225845036/pkg/mod/github.com/libp2p/go-libp2p-swarm@v0.4.0/swarm_listen.go:18 +0x204
    github.com/libp2p/go-libp2p/config.(*Config).NewNode(0x4000642600, 0x746c4282e0, 0x400066a000, 0xa, 0x0, 0x0, 0x1)
    	/tmp/gomobile-work-225845036/pkg/mod/github.com/libp2p/go-libp2p@v0.13.0/config/config.go:228 +0x168
    github.com/libp2p/go-libp2p.NewWithoutDefaults(0x746c4282e0, 0x400066a000, 0x40005b8730, 0xa, 0xa, 0x6, 0x6, 0x6, 0x746c3c9e00)
    	/tmp/gomobile-work-225845036/pkg/mod/github.com/libp2p/go-libp2p@v0.13.0/libp2p.go:71 +0x88
    github.com/libp2p/go-libp2p.New(...)
    	/tmp/gomobile-work-225845036/pkg/mod/github.com/libp2p/go-libp2p@v0.13.0/libp2p.go:57
    github.com/datahop/ipfs-lite.SetupLibp2p(0x746c4282e0, 0x400066a000, 0x746c42c1c0, 0x400000e0a0, 0x400066ad80, 0x3, 0x4, 0x746c42f340, 0x40000c4270, 0x746cc40ea0, ...)
    	/home/sabyasachi/go/src/github.com/datahop/ipfs-lite/util.go:81 +0x1e0
    github.com/datahop/ipfs-lite.New(0x746c4282e0, 0x400066a000, 0x746c422920, 0x40000bef40, 0x4000032620, 0x0, 0x0)
    	/home/sabyasachi/go/src/github.com/datahop/ipfs-lite/ipfs.go:98 +0x2b8
    github.com/datahop/ipfs-lite/mobile.Start.func1(0x746c422920, 0x40000bef40)
    	/home/sabyasachi/go/src/github.com/datahop/ipfs-lite/mobile/datahop.go:63 +0xa0
    created by github.com/datahop/ipfs-lite/mobile.Start
    	/home/sabyasachi/go/src/github.com/datahop/ipfs-lite/mobile/datahop.go:59 +0x110
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 11114 (ple.datahopdemo), pid 24760 (ple.datahopdemo)

**Comment by asabya** [comment]
This was happening due to older config. Things should be okay on a fresh install.
